#ifndef ERRORCODES_H
#define ERRORCODES_H


#define LEXICAL_ERROR 1
#define SYNTAX_ERROR 2
#define SEMANTIC_ERROR 3
#define SEMANTIC_EXPR_ERROR 4
#define SEMANTIC_PAR_ERROR 5
#define SEMANTIC_OTHERS_ERROR 6
#define DIVBYZERO_ERROR 9
#define INTERNAL_ERROR 99


#endif